- name: copy mongodb repo to yum.repos.d
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo
# here what will happen when ansible runs this  it will understand that it should go to the folder tasks and it will run it from there 
- name: Install mongodb
      ansible.builtin.yum:
        name: mongodb-org 
        state: installed
- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started 
    enabled: yes
- name: enable remote connections to mogodb
  ansible.builtin.replace: 
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: restart mongod
  ansible.builtin.service:
    name: mongod
    state: restarted 
