- name: copy mongodb repo to yum.repo.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell 
    state: installed

- name: loading {{component}} data
  ansible.builtin.command: mongo --host mongodb.awsdevopsjoin.online < /app/schema/{{component}}.js 