- name: copy mongodb repo to yum.repo.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

# To handle if the data already exists
# - name: Check if data exists
#   ansible.builtin.command: mongo --quiet --host mongodb.awsdevopsjoin.online --eval 'db.getMongo().getDBNames().indexOf("{{component}}");'
#   register: out

- name: load {{component}} data
  ansible.builtin.command: mongo --host mongodb.awsdevopsjoin.online < /app/schema/{{component}}.js
  #when: out.stdout == "-1"

# - name: Load Schema
#   community.mongodb.mongodb_shell:
#     login_host: mongodb.awsdevopsjoin.online
#     file: "/app/schema/{{component}}.js"
#     idempotent: yes
