- name: setup npm source
  ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

- name: Install Node.js with GPG check
  ansible.builtin.yum:
    name: nodejs
    state: installed
    disable_gpg_check: "{{ disable_gpg_check | default(false) }}"
  vars:
    disable_gpg_check: true # Set this to true if GPG checks need to be disabled

# - name: install Nodejs
#   ansible.builtin.yum:
#     name: nodejs
#     state: installed
#     # disable_gpg_check: "{{ disable_yum_gpg_check | d(omit) }}"
